config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get 'greeter/hello', to: 'greeter#hello'
  get 'greeter/goodbye', to: 'greeter#goodbye'

  root 'courses#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/coursera.rb
class Coursera
  include HTTParty

  #default_options.update(verify: false) # Turn off SSL verification
  base_uri 'https://jsonplaceholder.typicode.com'
  format :json

  def self.for (num)
    get("/photos", query: {albumId: num})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @search_term = params[:looking_for] || '1'
    @courses = Coursera.for(@search_term)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    name_array = ["Mary", "Alex", "Bob", "Sam"]
    @name = name_array.sample
    @time = Time.now
  end
  def goodbye

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
  def formatted_time(time)
    time.strftime("%I:%M%p")
  end
end

app/views/courses/index.html.erb
<h1>Searching for <%= @search_term %> album</h1>
<table border="1">
  <tr>
    <th>Thumbnail</th>
    <th>Title</th>
    <th>Url</th>
  </tr>
  <% @courses.each do |course| %>
    <tr>
      <td><%= image_tag(course["thumbnailUrl"])%></td>
      <td><%= course["title"] %></td>
      <td><%= course["url"] %></td>
    </tr>
  <% end %>
</table>

app/views/greeter/hello.html.erb
<h1>Greetings, <%= @name %></h1>
<p>The time is <%= formatted_time(@time)%></p>
<%= link_to "Goodbye", greeter_goodbye_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>